# rosy-sweep-52: /workspace/visiomel-2023/run/main_cv.py fit --config run/configs/sweeps/swin-patch-attention-classifier.yaml --data.init_args.batch_size=128 --data.init_args.sampler=weighted_upsampling --model.init_args.attention_dropout=0.04312334623490168 --model.init_args.attention_hidden_dim=128 --model.init_args.attention_num_heads=1 --model.init_args.label_smoothing=0.05843571552736478 --model.lr=0.002740351806608384 --trainer.max_epochs=100
name: endcmuao-seeds-ds-ll
program: run/main_cv.py
command:
  - ${env}
  - /root/miniconda3/envs/visiomel-2023/bin/python
  - ${program}
  - fit
  - --config
  - run/configs/sweeps/swin-patch-attention-classifier.yaml
  - ${args}
method: grid
metric:
  goal: minimize
  name: mean_best_val_ds_ll
parameters:
  trainer.max_epochs:
    distribution: categorical
    values: 
    - 100
  model.init_args.attention_hidden_dim:
    distribution: categorical
    values:
    - 128
  model.init_args.attention_num_heads:
    distribution: categorical
    values:
    - 1
  data.init_args.batch_size:
    distribution: categorical
    values:
    - 128
  data.init_args.sampler:
    distribution: categorical
    values:
    - weighted_upsampling
  model.init_args.attention_dropout:
    distribution: categorical
    values:
    - 0.04312334623490168
  model.lr:
    distribution: categorical
    values:
    - 0.002740351806608384
  model.init_args.label_smoothing:
    distribution: categorical
    values:
    - 0.05843571552736478
  data.init_args.split_seed:
    distribution: categorical
    values:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
