program: run/main_cv.py
command:
  - ${env}
  - /root/miniconda3/envs/visiomel-2023/bin/python
  - ${program}
  - fit
  - --config
  - run/configs/swin-patch-attention-classifier.yaml
  - ${args}
method: bayes
metric:
  goal: maximize
  name: val_f1
parameters:
  model.init_args.attention_hidden_dim:
    distribution: categorical
    values:
    - 32
    - 64
    - 128
    - 256
  model.lr:
    distribution: log_uniform_values
    max: 0.1
    min: 0.0001
  model.init_args.label_smoothing:
    distribution: uniform
    max: 0.3
    min: 0.0
  data.init_args.sampler:
    distribution: categorical
    values:
    - 'null'
    - weighted_upsampling