program: run/main_cv.py
command:
  - ${env}
  - /root/miniconda3/envs/visiomel-2023/bin/python
  - ${program}
  - fit
  - --config
  - run/configs/sweeps/swin-patch-attention-classifier.yaml
  - ${args}
method: random
parameters:
  trainer.max_epochs:
    distribution: categorical
    values: 
    - 200
  model.init_args.attention_hidden_dim:
    distribution: categorical
    values:
    - 256
  model.init_args.attention_num_heads:
    distribution: categorical
    values:
    - 8
  data.init_args.batch_size:
    distribution: categorical
    values:
    - 32
    - 64
    - 128
    - 256
  data.init_args.meta_filepath:
    distribution: categorical
    values:
    - /workspace/data/train_metadata_pPa7YD3.csv
    - none
  data.init_args.sampler:
    distribution: categorical
    values:
    - weighted_upsampling
  model.init_args.attention_dropout:
    distribution: uniform
    max: 0.2
    min: 0.1
  model.lr:
    distribution: log_uniform_values
    max: 3e-3
    min: 0.0001
  model.init_args.label_smoothing:
    distribution: uniform
    max: 0.15
    min: 0.0