# jz4aa305, leafy-sweep-44, best by ds pf1s: 
# /workspace/visiomel-2023/run/main_cv.py fit --config run/configs/sweeps/swin-patch-attention-classifier.yaml --data.init_args.batch_size=32 --data.init_args.meta_filepath=none --data.init_args.sampler=weighted_upsampling --model.init_args.attention_dropout=0.1769881341107499 --model.init_args.attention_hidden_dim=64 --model.init_args.attention_num_heads=8 --model.init_args.label_smoothing=0.06339042492159885 --model.lr=0.001351115896622556 --trainer.max_epochs=200
# https://wandb.ai/mkotyushev_/visiomel/runs/kp5xpmv5/overview?workspace=user-mkotyushev_
program: run/main_cv.py
command:
  - ${env}
  - /root/miniconda3/envs/visiomel-2023/bin/python
  - ${program}
  - fit
  - --config
  - run/configs/sweeps/nams2gt2-jz4aa305-nested-kfold/swin-patch-attention-classifier-val-ds-pf1s.yaml
  - ${args}
method: grid
parameters:
  trainer.max_epochs:
    distribution: categorical
    values: 
    - 200
  model.init_args.attention_hidden_dim:
    distribution: categorical
    values:
    - 64
  model.init_args.attention_num_heads:
    distribution: categorical
    values:
    - 8
  data.init_args.batch_size:
    distribution: categorical
    values:
    - 32
  data.init_args.meta_filepath:
    distribution: categorical
    values:
    - none
  data.init_args.sampler:
    distribution: categorical
    values:
    - weighted_upsampling
  model.init_args.attention_dropout:
    distribution: categorical
    values:
    - 0.1769881341107499
  model.lr:
    distribution: categorical
    values:
    - 0.001351115896622556
  model.init_args.label_smoothing:
    distribution: categorical
    values:
    - 0.06339042492159885
  data.init_args.k_test:
    distribution: categorical
    values:
    - 5
  data.init_args.fold_index_test:
    distribution: categorical
    values:
    - 0
    - 1
    - 2
    - 3
    - 4