# misty-sweep-3, best by ll, second best by ds-ll and pf1s: 
# /workspace/visiomel-2023/run/main_cv.py fit --config run/configs/sweeps/swin-patch-attention-classifier.yaml
# --data.init_args.batch_size=64
# --data.init_args.sampler=weighted_upsampling
# --model.init_args.attention_dropout=0.22373306482328575
# --model.init_args.attention_hidden_dim=128
# --model.init_args.attention_num_heads=4
# --model.init_args.label_smoothing=0.02997761314917208
# --model.lr=0.005034876576340356
# --trainer.max_epochs=200
# https://wandb.ai/mkotyushev_/visiomel/runs/wa58jacv/overview?workspace=user-mkotyushev_
name: misty-sweep-3-nested-kfold-save-ds-ll
program: run/main_cv.py
command:
  - ${env}
  - /root/miniconda3/envs/visiomel-2023/bin/python
  - ${program}
  - fit
  - --config
  - run/configs/swin-patch-attention-classifier-val-ds-ll.yaml
  - ${args}
method: grid
metric:
  goal: minimize
  name: mean_best_val_ds_ll
parameters:
  trainer.max_epochs:
    distribution: categorical
    values: 
    - 200
  model.init_args.attention_hidden_dim:
    distribution: categorical
    values:
    - 128
  model.init_args.attention_num_heads:
    distribution: categorical
    values:
    - 4
  data.init_args.batch_size:
    distribution: categorical
    values:
    - 64
  data.init_args.sampler:
    distribution: categorical
    values:
    - weighted_upsampling
  model.init_args.attention_dropout:
    distribution: categorical
    values:
    - 0.22373306482328575
  model.lr:
    distribution: categorical
    values:
    - 0.005034876576340356
  model.init_args.label_smoothing:
    distribution: categorical
    values:
    - 0.02997761314917208
  data.init_args.k_test:
    distribution: categorical
    values:
    - 5
  data.init_args.fold_index_test:
    distribution: categorical
    values:
    - 0
    - 1
    - 2
    - 3
    - 4