# pytorch_lightning==2.0.1
seed_everything: 0
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: visiomel
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    # - class_path: pytorch_lightning.callbacks.EarlyStopping
    #   init_args:
    #     monitor: val_f1
    #     patience: 30
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_f1
        save_top_k: 5
        save_on_train_epoch_end: false
        save_last: true

  precision: 32-true
  max_epochs: 30
  check_val_every_n_epoch: 5
  log_every_n_steps: 5
  gradient_clip_val: 10
  gradient_clip_algorithm: norm
  deterministic: true
  benchmark: false
  enable_checkpointing: true

  fast_dev_run: false
  limit_train_batches: null
  limit_val_batches: null
  profiler: null
  detect_anomaly: false
  
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  num_sanity_val_steps: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  inference_mode: true
  use_distributed_sampler: true
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
ckpt_path: null
model:
  class_path: src.model.swin_transformer_v2.SwinTransformerV2Classifier
  init_args:
    log_norm_verbose: true
    model_name: swinv2_base_window12to24_192to384_22kft1k
    num_classes: 2
    pretrained: true
    optimizer_init: 
      class_path: torch.optim.AdamW
      init_args:
        weight_decay: 1e-08
        eps: 1e-08
        lr: 4e-05
    lr_scheduler_init:
      class_path: src.utils.lr_scheduler.PiecewiceFactorsLRScheduler
      init_args:
        milestones: [0, 0.16, 1.0]
        pieces:
          - class_path: src.utils.lr_scheduler.LinearLRSchedulerPiece
            init_args:
              start_lr: 5e-4
              stop_lr: 0.5
          - class_path: src.utils.lr_scheduler.CosineLRSchedulerPiece
            init_args:
              start_lr: 0.5
              stop_lr: 5e-3
    pl_lrs_cfg:
      interval: step
      frequency: 1
data:
  class_path: src.data.visiomel_datamodule.VisiomelTrainDatamodule
  init_args:
    data_dir_train: /workspace/data/images_page_7/
    img_size: 1024
    k: 5
    fold_index: 0
    data_dir_test: null
    split_seed: 0
    num_workers: 10
    pin_memory: false
    prefetch_factor: 2
    sampler: weighted_upsampling
    shrink_preview_scale: null
    batch_size: 8
