model:
  class_path: src.model.quadtree_classifier.QuadtreeClassifier
  init_args:
    backbone_name: resnet18
    finetuning:
      unfreeze_before_epoch: 500
      unfreeze_layer_names_startswith:
        - embedding.splitter
        - classifier
data:
  class_path: src.data.visiomel_datamodule.VisiomelTrainDatamodule
  init_args:
    data_dir_train: /workspace/data/images_page_7/
    img_size: 1024
    k: 5
    fold_index: 0
    data_dir_test: null
    split_seed: 0
    num_workers: 10
    pin_memory: false
    prefetch_factor: 2
    sampler: weighted_upsampling
    shrink_preview_scale: null
    batch_size: 8
