model:
  init_args:
    model_name: swinv2_base_window12to24_192to384_22kft1k
    patch_embed_backbone_name: null
    patch_size: 4
    finetuning:
      unfreeze_before_epoch: 0
      unfreeze_layer_names_startswith:
        - model.head
data:
  init_args:
    data_dir_train: /workspace/data/images_page_7/
    img_size: 768
    shrink_preview_scale: null
    batch_size: 2
    enable_caching: true
