model:
  init_args:
    patch_embed_backbone_name: null
    patch_size: 4
    finetuning:
      unfreeze_after_epoch: 10
      unfreeze_layer_names_startswith:
        - model.head
data:
  init_args:
    data_dir_train: /workspace/data/images_page_7/
    img_size: 256
    shrink_preview_scale: null
    batch_size: 64
trainer:
  check_val_every_n_epoch: 1
