# pytorch_lightning==2.0.1
seed_everything: 0
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: visiomel
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 5    
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        save_top_k: 5
        save_on_train_epoch_end: false
        save_last: true

  precision: 16-mixed
  max_epochs: 400
  check_val_every_n_epoch: 10
  log_every_n_steps: 50
  gradient_clip_val: 100
  gradient_clip_algorithm: norm
  deterministic: true
  benchmark: false
  enable_checkpointing: true

  # Debugging
  fast_dev_run: false
  limit_train_batches: null
  limit_val_batches: null
  profiler: null
  detect_anomaly: false

  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  num_sanity_val_steps: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  inference_mode: true
  use_distributed_sampler: true
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
ckpt_path: null
model:
  class_path: src.model.swin_transformer_v2.SwinTransformerV2Classifier
  init_args:
    model_name: swinv2_tiny_window8_256
    num_classes: 2
data:
  class_path: src.data.visiomel_datamodule.VisiomelTrainDatamodule
  init_args:
    data_dir_train: /workspace/data/images_page_7/
    k: 5
    fold_index: 0
    data_dir_test: null
    img_size: 1024
    batch_size: 2
    split_seed: 0
    num_workers: 10
    pin_memory: false
