model:
  init_args:
    patch_embed_backbone_name: null
    patch_size: 4
data:
  init_args:
    data_dir_train: /workspace/data/images_page_7/
    img_size: 1024
    shrink_preview_scale: null
    batch_size: 4
trainer:
  max_epochs: 50
  check_val_every_n_epoch: 1
