model:
  init_args:
    patch_embed_backbone_name: resnet18
    patch_size: 96
    finetuning:
      unfreeze_after_epoch: 50
      unfreeze_layer_names_startswith:
        - patch_embed.proj.linear
        - head
data:
  init_args:
    data_dir_train: /workspace/data/images_page_5/
    img_size: 3072
    shrink_preview_scale: 4
    batch_size: 6
    num_workers: 6