trainer:
  # limit_train_batches: 10
  # limit_val_batches: 10
  max_epochs: 100
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
  reload_dataloaders_every_n_epochs: 0
  log_every_n_steps: 10
  gradient_clip_val: 20
  check_val_every_n_epoch: 1
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        monitor: val_ds_ll
        every_n_epochs: 1
        mode: min
        save_on_train_epoch_end: false
        save_last: true
model:
  class_path: src.model.patch_attention_classifier.PatchAttentionClassifier
  init_args:
    grad_checkpointing: true
    patch_embed_backbone_name: swinv2_base_window12to24_192to384_22kft1k
    patch_embed_backbone_ckpt_path: /workspace/visiomel-2023/weights/val_ssup_patches/checkpoints/last.ckpt
    patch_size: 1536
    patch_batch_size: 16
    attention_hidden_dim: 256
    patch_embed_caching: false
    emb_precalc: true
    emb_precalc_dim: 1024
    optimizer_init: 
      class_path: torch.optim.AdamW
      init_args:
        weight_decay: 0.01
        eps: 1e-08
        lr: 1e-3
    lr_scheduler_init:
      class_path: src.utils.lr_scheduler.PiecewiceFactorsLRScheduler
      init_args:
        milestones: [0, 0.1, 1.0]
        pieces:
          - class_path: src.utils.lr_scheduler.LinearLRSchedulerPiece
            init_args:
              start_lr: 1e-2
              stop_lr: 1
          - class_path: src.utils.lr_scheduler.CosineLRSchedulerPiece
            init_args:
              start_lr: 1
              stop_lr: 1e-2
    pl_lrs_cfg:
      interval: step
      frequency: 1
    lr_layer_decay: 1.0
    finetuning:
      unfreeze_before_epoch: 5000
      unfreeze_layer_names_startswith:
        - pooling
        - classifier
data:
  class_path: src.data.visiomel_datamodule_emb.VisiomelDatamoduleEmb
  init_args:
    embedding_pathes: 
      - /workspace/visiomel-2023/weights/val_ssup_patches_aug_fold_0/embeddings/train.pkl
      - /workspace/visiomel-2023/weights/val_ssup_patches_aug_fold_0/embeddings/val_aug.pkl
    k: 5
    fold_index: 0
    split_seed: 0
    batch_size: 32
    num_workers: 10
    num_workers_saturated: 10
    prefetch_factor: 2
    pin_memory: false
    sampler: weighted_upsampling
