model:
  class_path: src.model.timm_classifier.TimmClassifier
  init_args:
    backbone_name: resnet50
    num_classes: 2
    pretrained: true
    lr_layer_decay: 0.9
data:
  class_path: src.data.visiomel_datamodule.VisiomelTrainDatamodule
  init_args:
    data_dir_train: /workspace/data/images_page_7/
    img_size: 1024
    num_workers: 10
    shrink_preview_scale: null
    batch_size: 32
